OBG 797: FinTech server responds 500 on BankSearch when there are no matching results
adorsys/open-banking-gateway pull request #1011
Opened 2020-09-16 07:46 UTC by ivaniuminov

https://github.com/adorsys/open-banking-gateway/issues/797

2020-09-18 07:54 UTC, valb3r requested changes
Missing:
![Selection_136](https://user-images.githubusercontent.com/18463491/93571587-576a7e00-f99d-11ea-8910-1e26c6143c27.png)

2020-09-28 08:53 UTC, valb3r approved these changes

2020-09-28 08:53 UTC, valb3r commented on opba-banking-rest-impl/src/test/java/de/adorsys/opba/tppbankingapi/service/BankServiceTest.java
> +
Extra whitespace

2020-09-28 11:08 UTC, ivaniuminov commented on opba-banking-rest-impl/src/test/java/de/adorsys/opba/tppbankingapi/service/BankServiceTest.java
> +
Removed. thanks

2020-09-28 13:58 UTC, merged